-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQ4mEhdZw/M+scDnN
nq11+t+gq0b7vIHKv/iDo5zX/DKgCgYIKoZIzj0DAQehRANCAARUGWn7ODfGfUpZ
2WXeK5cfUZ/DNoT7E6KmjGzIT5v7O9fvzpjvZRv4bYcyZ/ZRWsVwMC+e/I0CL/Yw
H4xptvG6
-----END PRIVATE KEY-----